/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const CustomCategory = IDL.Variant({
  'graduate' : IDL.Null,
  'dPharm' : IDL.Null,
  'bPharm' : IDL.Null,
  'mPharm' : IDL.Null,
});
export const NoteMetaData = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'blob' : ExternalBlob,
  'description' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'timestamp' : Time,
  'category' : CustomCategory,
  'uploader' : IDL.Principal,
  'isPublic' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'dob' : IDL.Text,
  'name' : IDL.Text,
  'course' : CustomCategory,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBookmark' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createNote' : IDL.Func([NoteMetaData], [], []),
  'createOrUpdateProfile' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, CustomCategory],
      [],
      [],
    ),
  'deleteNote' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAllNotes' : IDL.Func([], [IDL.Vec(NoteMetaData)], ['query']),
  'getBookmarkedNotes' : IDL.Func([], [IDL.Vec(NoteMetaData)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeaturedNotes' : IDL.Func([], [IDL.Vec(NoteMetaData)], ['query']),
  'getNoteById' : IDL.Func([IDL.Text], [IDL.Opt(NoteMetaData)], ['query']),
  'getNotesByCategory' : IDL.Func(
      [CustomCategory],
      [IDL.Vec(NoteMetaData)],
      ['query'],
    ),
  'getRecentNotes' : IDL.Func([], [IDL.Vec(NoteMetaData)], ['query']),
  'getUserNotes' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(NoteMetaData)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeBookmark' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateNote' : IDL.Func([IDL.Text, NoteMetaData], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const CustomCategory = IDL.Variant({
    'graduate' : IDL.Null,
    'dPharm' : IDL.Null,
    'bPharm' : IDL.Null,
    'mPharm' : IDL.Null,
  });
  const NoteMetaData = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'blob' : ExternalBlob,
    'description' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'timestamp' : Time,
    'category' : CustomCategory,
    'uploader' : IDL.Principal,
    'isPublic' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'dob' : IDL.Text,
    'name' : IDL.Text,
    'course' : CustomCategory,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBookmark' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createNote' : IDL.Func([NoteMetaData], [], []),
    'createOrUpdateProfile' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, CustomCategory],
        [],
        [],
      ),
    'deleteNote' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAllNotes' : IDL.Func([], [IDL.Vec(NoteMetaData)], ['query']),
    'getBookmarkedNotes' : IDL.Func([], [IDL.Vec(NoteMetaData)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeaturedNotes' : IDL.Func([], [IDL.Vec(NoteMetaData)], ['query']),
    'getNoteById' : IDL.Func([IDL.Text], [IDL.Opt(NoteMetaData)], ['query']),
    'getNotesByCategory' : IDL.Func(
        [CustomCategory],
        [IDL.Vec(NoteMetaData)],
        ['query'],
      ),
    'getRecentNotes' : IDL.Func([], [IDL.Vec(NoteMetaData)], ['query']),
    'getUserNotes' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(NoteMetaData)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeBookmark' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateNote' : IDL.Func([IDL.Text, NoteMetaData], [], []),
  });
};

export const init = ({ IDL }) => { return []; };