/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CustomCategory = { 'graduate' : null } |
  { 'dPharm' : null } |
  { 'bPharm' : null } |
  { 'mPharm' : null };
export type ExternalBlob = Uint8Array;
export interface NoteMetaData {
  'id' : string,
  'title' : string,
  'blob' : ExternalBlob,
  'description' : string,
  'isFeatured' : boolean,
  'timestamp' : Time,
  'category' : CustomCategory,
  'uploader' : Principal,
  'isPublic' : boolean,
}
export type Time = bigint;
export interface UserProfile {
  'age' : bigint,
  'dob' : string,
  'name' : string,
  'course' : CustomCategory,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBookmark' : ActorMethod<[string], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createNote' : ActorMethod<[NoteMetaData], undefined>,
  'createOrUpdateProfile' : ActorMethod<
    [string, bigint, string, CustomCategory],
    undefined
  >,
  'deleteNote' : ActorMethod<[string], boolean>,
  'getAllNotes' : ActorMethod<[], Array<NoteMetaData>>,
  'getBookmarkedNotes' : ActorMethod<[], Array<NoteMetaData>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeaturedNotes' : ActorMethod<[], Array<NoteMetaData>>,
  'getNoteById' : ActorMethod<[string], [] | [NoteMetaData]>,
  'getNotesByCategory' : ActorMethod<[CustomCategory], Array<NoteMetaData>>,
  'getRecentNotes' : ActorMethod<[], Array<NoteMetaData>>,
  'getUserNotes' : ActorMethod<[Principal], Array<NoteMetaData>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeBookmark' : ActorMethod<[string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateNote' : ActorMethod<[string, NoteMetaData], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];